### ISSUE TITLE
Default mode for arc() is PIE, not OPEN

### ISSUE THREAD

**Issue by sebhunt** [processing/processing-web-archive#257]
The <a href="http://processing.org/reference/arc_.html">reference for arc()</a> states that the default drawing mode is OPEN. It actually seems to be PIE.

**Comment by ewelinka** [comment]
A comment: it's a little bit confusing to have an initial setting (PIE fill + OPEN stroke) that is imposible to set if you, for example, first defined an arc in OPEN, PIE or CHORD mode and THEN, after drawing the first arc you want to draw an arc with PIE fill + OPEN stroke.

**Comment by REAS** [comment]
This isn't an active repository. Please post documentation issues here: https://github.com/processing/processing-docs
