### ISSUE TITLE
Error in Processing refference for ellipse??...HELP

### ISSUE THREAD

**Issue by budski82** [processing/processing-web-archive#446]
I am new here and using the Getting Started with Processing .pdf. I was following along and using the PDE and drawing ellipses when I used: Find Reference from the Edit tab for more of an explanation. Of the ellipseMode(); function and their differences. A bit confused as the visual diagram examples it provides are opposite of the typed explained differences. It said in RADIUS mode it uses HALF the third and forth parameters to set it width and height. But show a diagram for ellipseMode(CENTER); as the one with HALF the third and forth parameters. As if they are reversed by mistake or I am very confused. I am very new to any coding and dont want to assume anything. I enclosed a screen shot and just looking to see if in fact they are just labeled incorrectly. Thanks for any and all explanations...Peace.....

[git_help](https://cloud.githubusercontent.com/assets/6143305/6220219/ca9a638a-b601-11e4-9570-cf8b7ae01780.jpg)
!!

**Comment by REAS** [comment]
The language might not be clear, but the code and the images are correct. Cut and paste the code and run to confirm. This repo, the "processing-web-archive" is an archive. Please report bugs at processing/processing-docs

**Comment by budski82** [comment]
Thanks for the reply and I will use the second repo for know on, or if need be. Still confused though?? Both examples are using 30 as both the third and forth parameters. If ellipseMode(RADIUS)uses  the third and forth parameters to specify half the shapes width and height. My brain is telling me that half of 30 is 15 and the two images should be switched. Because ellipseMode(CENTER) uses the entire value of the parameter to set the width and height. I have been told I see things differently but does this make sense to you?? If you could offer an explanation as I cant get over what my eyes tell me these are backward.
 
Date: Mon, 16 Feb 2015 20:25:44 -0800
