### ISSUE TITLE
Forum redirect not working over HTTPS

### ISSUE THREAD

**Issue by javl** [processing/processing-web-archive#447]
I guess this is a low-priority bug:
I'm using the EFF's 'HTTPS Everywhere' browser extension, which forces your browser to always favor a HTTPS connection over a HTTP one (if available). With the plugin enabled, I'm not able to visit the forums because https://forum.processing.org does exist (and so is used by the extension) but it does not redirect me to the forum - it just shows the Processing homepage. I need to visit http://forum.processing.org instead.

Though it's the extension that forces me to use the HTTPS page, I think the page not redirecting is still an error on the Processing server.

**Comment by alignedleft** [comment]
This repo (processing-web-archive) is an *archive* and no longer monitored.

If you want to post an issue with the forums, please go to: https://github.com/processing/processing-forum/issues/
