### ISSUE TITLE
Problem with search box

### ISSUE THREAD

**Issue by ghufransyed** [processing/processing-web-archive#448]
It works on the front page (processing.org), if I enter 'rect' in the search box, it redirects to google with rect as the search parameter, at 
https://www.google.com/search?as_sitesearch=processing.org&as_q=rect
If I click on the first link given, I get the following page:
https://processing.org/reference/rect_.html
If I enter 'rect' again in the search box, I get a 404:
Not Found

The requested URL /reference/www.google.com/search was not found on this server.

Apache/2.4.7 (Ubuntu) Server at processing.org Port 443

**Comment by alignedleft** [comment]
@ghufransyed Great catch. Thanks. I'm looking into this.

**Comment by REAS** [comment]
We should move this over to processing-docs. This repo is no longer active.

**Comment by alignedleft** [comment]
Oops! Meant to do that first. Thanks, will do.
