### ISSUE TITLE
Hi, all

### ISSUE THREAD

**Issue by PaulOrlov** [processing/processing-web-archive#450]
A few month ago I published the book "Programming for Artists" and shared it with CC licence. Here is a discussion about this book: https://forum.processing.org/two/discussion/14888/new-book-about-processing-programming-for-artists#latest

I would like to bring it to the https://processing.org/books/ , is it possible? You can find all information about the book here: http://ptahi.ru/2016/02/07/programming-for-artists/

Thanks for you help!

**Comment by alignedleft** [comment]
Please post in: https://github.com/processing/processing-docs/issues/

This repo is no longer used. :-)
