### ISSUE TITLE
Duplicate Library on Libraries Page

### ISSUE THREAD

**Issue by softpunch** [processing/processing-web-archive#451]
On the **Libraries** page, "Most Pixels Ever" is listed twice.

https://processing.org/reference/libraries/

![screen-shot-2016-08-30-at-1 32 48-pm](https://cloud.githubusercontent.com/assets/19437970/18099939/d79e8164-6eb6-11e6-8f42-5dd3355320ea.jpg)

**Comment by alignedleft** [comment]
Thanks for the heads-up! cc @prisonerjohn FYI

Closing this issue, as this repo is no longer maintained. The new place to log issues with the reference is: https://github.com/processing/processing-docs/
