### ISSUE TITLE
minor grammatical error in lerp() reference

### ISSUE THREAD

**Issue by bam-suffolk** [processing/processing-web-archive#453]
Minor grammatical error in Processing reference for **lerpColor()**

[file:///Applications/ExtraApps/Processing.app/Contents/Java/modes/java/reference/lerpColor_.html
](url)

> Calculates a color or colors between two color at a specific increment. 
should be:
> Calculates a color or colors between two color**s** at a specific increment.

**Comment by REAS** [comment]
This is no longer an active repo, but I made the correction to the current file. Thank you for reporting. Please post in the future to /processing/processing-web/
